@startuml communication_format_example
actor Actor
participant mqtt_door_topic
participant door

Actor -> mqtt_door_topic: trigger: on
mqtt_door_topic -> door: trigger: on
door -> mqtt_door_topic: state: active [opening]
loop [on door is not opened]
    door -> door: sliding on
end

door -> mqtt_door_topic: state: inactive [opened]
@enduml