@startuml group_4_door
actor Actor
participant mqtt_door_topic
participant door
note over mqtt_door_topic, door
    <mqtt_door_topic> and <door> are placeholders
    for their instances (ex. MQTT_4_door_entrance)
end note

== Init ==
door -> mqtt_door_topic: register

== Open door ==
Actor -> mqtt_door_topic: trigger: on
mqtt_door_topic -> door: trigger: on
door -> mqtt_door_topic: status: active [opening]
loop door is not opened
    door -> door: opening
else on error
    door -> mqtt_door_topic: status: failed [error_json]
else on opened
    door -> mqtt_door_topic: status: inactive [opened]
end

== Close door ==
Actor -> mqtt_door_topic: trigger: off
mqtt_door_topic -> door: trigger: off
door -> mqtt_door_topic: status: active [closing]
loop door is not closed
    door -> door: closing
else on error
    door -> mqtt_door_topic: status: failed [error_json]
else on closed
    door -> mqtt_door_topic: status: inactive [closed]
end
@enduml