@startuml group_4_puzzle_entrance_door
actor operator
participant MQTT_4_door_entrance_puzzle
participant puzzle
participant MQTT_4_door_entrance

== Init ==
puzzle -> MQTT_4_door_entrance_puzzle: register

== Solve puzzle ==
operator -> MQTT_4_door_entrance_puzzle: trigger: on
MQTT_4_door_entrance_puzzle -> puzzle: trigger: on
puzzle -> MQTT_4_door_entrance_puzzle: status: active

loop input wrong key
    alt kepad input
        puzzle -> MQTT_4_door_entrance_puzzle: status: active [input]
    end
else input correct key
    puzzle -> MQTT_4_door_entrance_puzzle: status: solved
    MQTT_4_door_entrance_puzzle -> operator: status: solved
else on error
    puzzle -> MQTT_4_door_entrance_puzzle: status: failed [error_json]
end

== Open entrance door  ==
operator -> MQTT_4_door_entrance: trigger: on
@enduml